# Generated by Django 5.0.6 on 2024-07-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
